django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('foods.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foods/urls.py
from django.urls import path, include

from . import user_views, dish_views, menu_views

urlpatterns = [
    path('', dish_views.AllPublicDishView.as_view(), name='index'),
    path('accounts/', include([
        path('register/', user_views.RegisterView.as_view(), name='register'),
    ])),
    path('users/', include([
        path('profile/', user_views.UpdateProfileView.as_view(), name='account_profile'),
        path('dish/', include([
            path('', dish_views.UserAllDishView.as_view(), name='user_all_dishes'),
            path('add/', dish_views.CreateDishView.as_view(), name='user_add_dish'),
            path('<int:pk>/', include([
                path('', dish_views.UserDishView.as_view(), name='user_dish_detail'),
                path('update/', dish_views.UpdateDishView.as_view(), name='user_update_dish'),
                path('delete/', dish_views.DeleteDishView.as_view(), name='user_delete_dish')
            ]))
        ]))
    ])),
    path('admins/', include([
        # path('', admin_views.Index.as_view(), name='admin_index'),
        # path('user/', admin_views.UserManagement.as_view(), name='user_management'),
        path('profile/', user_views.AdminSearchProfile.as_view(), name='admin_search_profile'),
        path('dish/', include([
            path('', dish_views.AdminAllDishView.as_view(), name='admin_all_dishes'),
            path('add/', dish_views.CreateDishView.as_view(), name='admin_add_dish'),
            path('<int:pk>/', include([
                path('', dish_views.AdminDishView.as_view(), name='admin_dish_detail'),
                path('update/', dish_views.UpdateDishView.as_view(), name='admin_update_dish'),
                path('delete/', dish_views.DeleteDishView.as_view(), name='admin_delete_dish')
            ]))
        ])),
    ])),
    path('dish/', include([
        path('', dish_views.SearchDishView.as_view(), name='search_dish'),
        path('<int:pk>/', include([
            path('', dish_views.DishDetailView.as_view(), name='dish_detail'),
            path('rate/', dish_views.UserRatingView.as_view(), name='user_rating'),
            path('delete/', dish_views.SuperuserDeleteDishView.as_view(), name='self_delete_dish')
        ])),
    ])),
    path('profile/', include([
        path('', user_views.SearchProfile.as_view(), name='search_profile'),
        path('<int:pk>/', include([
            path('', user_views.ProfileView.as_view(), name='profile_detail'),
            path('activate/', user_views.UpdateActivationView.as_view(), name='update_activation')
        ])),
    ])),

    path('menu/', include([
        path('', menu_views.index.as_view(), name="menu_index"),
        path('create', menu_views.create.as_view(), name="menu_create"),
        path('create_query', menu_views.create_query.as_view(), name="menu_create_query"),
        path('update_query', menu_views.update_query.as_view(), name="menu_update_query"),
        path('clone_query', menu_views.clone_query.as_view(), name="menu_clone_query"),
        path('delete_query', menu_views.delete_query.as_view(), name="menu_delete_query"),
        path('history', menu_views.history.as_view(), name="menu_history"),
        path('detail/<int:menu_id>', menu_views.detail.as_view(), name="menu_detail"),
        path('update', menu_views.update.as_view(), name="menu_update"),
        path('delete', menu_views.delete.as_view(), name="menu_delete"),
        path('query_filter_dish', menu_views.query_filter_dish, name="menu_query_filter_dish")
    ]))
]

handler404 = 'foods.views.error_404'
handler500 = 'foods.views.error_500'

foods/models.py
from django.contrib.auth.models import User as BaseUser
from django.db import models

from foods.validators import dish_image_path


class User(models.Model):
    user = models.OneToOneField(BaseUser, on_delete=models.CASCADE)
    birthday = models.DateField()
    height = models.IntegerField()
    weight = models.IntegerField()
    gender = models.BooleanField()
    diet_factor = models.FloatField()

    def __str__(self):
        return self.user.username

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=models.Q(weight__gt=0),
                name='weight_gt_0'
            ),
            models.CheckConstraint(
                check=models.Q(height__gt=100),
                name='height_gt_100'
            ),
            models.CheckConstraint(
                check=models.Q(diet_factor__gt=0),
                name='diet_factor_gt_0'
            )
        ]


class Dish(models.Model):
    user = models.ForeignKey(BaseUser, on_delete=models.CASCADE)
    dish_name = models.CharField(max_length=50)
    description = models.CharField(max_length=500)
    calories = models.IntegerField()
    is_public = models.BooleanField()
    image = models.ImageField(
        upload_to=dish_image_path
    )
    ingredients = models.CharField(max_length=250)
    score = models.FloatField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.dish_name

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=models.Q(calories__gt=0),
                name='calories_gt_0'
            ),
            models.CheckConstraint(
                check=models.Q(score__gte=0),
                name='dish_score_gte_0'
            ),
            models.CheckConstraint(
                check=models.Q(score__lte=5),
                name='dish_score_lte_5'
            )
        ]
        ordering = ['-updated_at']


class Rating(models.Model):
    user = models.ForeignKey(BaseUser, on_delete=models.CASCADE)
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE)
    score = models.IntegerField()
    comment = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user.pk}-{self.dish.pk}'

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=models.Q(score__gt=0),
                name='rating_score_gt_0'
            ),
            models.CheckConstraint(
                check=models.Q(score__lte=5),
                name='rating_score_lte_5'
            ),
        ]
        unique_together = ('user', 'dish')
        ordering = ['-updated_at']


class Menu(models.Model):
    user = models.ForeignKey(BaseUser, on_delete=models.CASCADE)
    description = models.CharField(max_length=250)
    mealtime = models.DateTimeField()
    limit = models.IntegerField()
    dishes = models.ManyToManyField(Dish, null=True, through="Menu_Dish")

    # calories it not necessary but db keep it in local, i am not able to fix it
    calories = models.IntegerField(default=0)


class Menu_Dish(models.Model):
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE)
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE)
    count = models.IntegerField(default=1)

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=models.Q(count__gt=0),
                name="count_gt_0"
            )
        ]

templates/dish.html
{% extends "base.html" %}

{% block title %}Dish{% endblock %}

{% block content %}
<div class="row m-5">
    <div class="col-lg-6">
        <img class="card-img-top" src="/media/{{ object.image|default:"default.jpg" }}" alt="Không có hình ảnh">
    </div>
    <div class="col-lg-6">
        <div class="d-flex justify-content-center">
            <h2 class="text-uppercase">{{ object.dish_name }}</h2>
        </div>
        <table class="table table-hover">
            <tr>
                <th>Người sở hữu:</th>
                <td><a href="{% url 'profile_detail' object.user.pk %}">{{ object.user }}</a></td>
            </tr>
            <tr>
                <th>Mô tả:</th>
                <td>{{ object.description }}</td>
            </tr>
            <tr>
                <th>Lượng calories:</th>
                <td>{{ object.calories }} kcal</td>
            </tr>
            <tr>
                <th>Trạng thái:</th>
                <td>{{ object.is_public|yesno:"Công khai, Riêng tư" }}</td>
            </tr>
            <tr>
                <th>Thành phần:</th>
                <td>{{ object.ingredients }}</td>
            </tr>
            <tr>
                <th>Đánh giá trung bình:</th>
                <td><span class="mr-2">{{ object.score }}/5</span><i class="fas fa-star"></i></td>
            </tr>
        </table>
        <div class="row m-3 d-flex justify-content-center">
            {% if user.is_authenticated %}
            {% if user != object.user and not user.is_staff %}
            <a type="button" class="btn btn-secondary m-2" data-toggle="modal" data-target="#form">Đánh giá</a>
            <div class="modal fade" id="form" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="card-body text-center">
                            <div class="text-center">
                                <form action="rate/" method="post">
                                    {% csrf_token %}
                                    <h4>Thêm đánh giá cho món ăn</h4>
                                    <div class="mb-2">
                                        <input type="number" min="1" max="5" step="1"
                                            value="{{ user_rating.score|default:5 }}" id="rating" name="score">
                                        <label for="rating">
                                            <i class="fas fa-star"></i>
                                        </label>
                                    </div>
                                    <div class="comment-area">
                                        <label>
                                            <textarea class="form-control" placeholder="Thêm bình luận" rows="4"
                                                name="comment" maxlength="100">{{ user_rating.comment }}</textarea>
                                        </label>
                                    </div>
                                    <div class="text-center mt-4">
                                        <button class="btn btn-success" type="submit">Gửi</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% else %}
            <a type="button" class="btn btn-primary m-2" href="{% url 'user_update_dish' object.id %}">Chỉnh sửa</a>
            <a type="button" class="btn btn-danger m-2" href="#" data-toggle="modal" data-target="#confirmModal">Xóa</a>
            {% endif %}
            {% endif %}
        </div>
    </div>
</div>

<div class="row d-flex justify-content-center m-5">
    <div class="panel panel-default w-100">
        <div class="panel-heading">
            <h3 class="panel-title">Đánh giá bởi người dùng</h3>
        </div>
        <div class="panel-body">
            <ul class="list-group">
                {% for dish in page_obj.object_list %}
                <li class="list-group-item">
                    <div>
                        <a href="{% url 'profile_detail' dish.user.pk %}">{{ dish.user }}</a>
                        <div>
                            <span>{{ dish.score }}</span>
                            <i class="fas fa-star"></i>
                        </div>
                        <div class="comment-text">
                            <span>{{ dish.comment }}</span>
                        </div>
                        <div>
                            <span>{{ dish.updated_at }}</span>
                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>
            <div class="mb-4">
                <div class="pagination d-flex justify-content-center">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                        <a class="btn btn-primary" href="?page=1">&laquo; first</a>
                        <a class="btn btn-primary" href="?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}

                        <span class="current">
                            <button class="btn btn-secondary" disabled>Page {{ page_obj.number }} of
                                {{page_obj.paginator.num_pages }}</button>
                        </span>

                        {% if page_obj.has_next %}
                        <a class="btn btn-primary" href="?page={{ page_obj.next_page_number }}">next</a>
                        <a class="btn btn-primary" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/dishes.html
{% extends "base.html" %}

{% load static %}

{% block title %}Dishes{% endblock %}

{% block content %}
<div class="row">
    {% for dish in page_obj.object_list %}
    <div class="col-lg-4 col-md-6 mb-4">
        <div class="card h-100">
            <div class="h-75 d-flex align-items-center">
                <a href="#"><img class="card-img-top" src="/media/{{ dish.image|default:"default.jpg" }}" alt="Không có hình ảnh"></a>
            </div>
            <div class="card-body">
                <h4 class="card-title">
                    <a href="{% url 'dish_detail' dish.pk %}">{{ dish.dish_name }}</a>
                </h4>
                <h5>{{dish.calories}} kcal</h5>
                <p class="card-text">{{ dish.description }}</p>
            </div>
            <div class="card-footer">
                <small class="text-muted">Đánh giá trung bình: {{dish.score}}/5</small>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<div class="mb-4">
    <div class="pagination d-flex justify-content-center">
        <span class="step-links">
            {% if page_obj.has_previous %}
            <a class="btn btn-primary" href="?page=1">&laquo; first</a>
            <a class="btn btn-primary" href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                <button class="btn btn-secondary" disabled>
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages}}
                </button>
            </span>

            {% if page_obj.has_next %}
            <a class="btn btn-primary" href="?page={{ page_obj.next_page_number }}">next</a>
            <a class="btn btn-primary" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock %}

templates/error.html
{% extends 'base.html' %}
{% block title %}
    Lỗi
{% endblock title %}
{% block app_name %}
    Lỗi tải trang
{% endblock app_name %}
{% block content %}
        <script src="{% static 'js/js.cookie.min.js' %}" defer></script>
    <div class="container-fluid" style="height:750px">
        <h3>
            Không tải được trang
        </h3>

    </div>
{% endblock content %}

    

templates/index.html
{% extends "base.html" %}

{% block title %}Foods{% endblock %}

{% block content %}

    <h1>Edit here!</h1>

{% endblock %}

templates/profile.html
{% extends "base.html" %}

{% block title %}Foods{% endblock %}

{% block content %}
    <div class="m-5">
        <h2 class="text-center mb-5">Thông tin người dùng</h2>
        <table class="table table-hover">
            <tr>
                <th>Tên đăng nhập:</th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>Email:</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Họ tên:</th>
                <td>{{ user.last_name }} {{ user.first_name }}</td>
            </tr>
            <tr>
                <th>Ngày sinh:</th>
                <td>{{ user.user.birthday|date:"d/m/Y" }}</td>
            </tr>
            <tr>
                <th>Giới tính:</th>
                <td>{{ user.user.gender|yesno:"Nam, Nữ" }}</td>
            </tr>
            <tr>
                <th>Chiều cao:</th>
                <td>{{ user.user.height }} cm</td>
            </tr>
            <tr>
                <th>Chiều cao:</th>
                <td>{{ user.user.weight }} kg</td>
            </tr>
            <tr>
                <th>Hệ số ăn uống:</th>
                <td>{{ user.user.diet_factor }}</td>
            </tr>
            <tr>
                <th>Trạng thái tài khoản:</th>
                <td>
                    <div class="mb-3">{{ user.is_active|yesno:"Hoạt động, Khóa" }}</div>
                    {% if request.user.is_authenticated and request.user.is_staff %}
                        <form action="activate/" method="post">
                            {% csrf_token %}
                            {% if user.is_active %}
                                <input class="btn btn-danger" type="submit" value="Khoá tài khoản">
                            {% else %}
                                <input class="btn btn-success" type="submit" value="Mở khoá tài khoản">
                            {% endif %}
                        </form>
                    {% endif %}
                </td>
            </tr>
        </table>
    </div>
{% endblock %}

templates/profiles.html
{% extends "base.html" %}

{% block title %}Foods{% endblock %}

{% block content %}
    <div class="row">
        {% for user in page_obj.object_list %}
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card h-100">
                    <div class="card-body">
                        <h4 class="card-title">
                            <a href="{% url 'profile_detail' user.pk %}">{{ user.username }}</a>
                        </h4>
                        <h5>{{ user.last_name }} {{ user.first_name }}</h5>
                        <p class="card-text">{{ user.email }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="mb-4">
        <div class="pagination d-flex justify-content-center">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a class="btn btn-primary" href="?page=1">&laquo; first</a>
                <a class="btn btn-primary" href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                <button class="btn btn-secondary" disabled>
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                </button>
            </span>

            {% if page_obj.has_next %}
                <a class="btn btn-primary" href="?page={{ page_obj.next_page_number }}">next</a>
                <a class="btn btn-primary" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
        </div>
    </div>
{% endblock %}

templates/rating_form.html
{% extends "base.html" %}

{% block title %}Ratings{% endblock %}

{% block content %}
    <form class="m-5" action="" method="post">
        {% csrf_token %}
        <div class="form-group row">
            <label for="id_height" class="col-sm-2 col-form-label">Score</label>
            <div class="col-sm-10">
                <input type="number" class="form-control" id="id_height" name="score" min="1" max="5" value="{{ rating.score }}"
                       required>
            </div>
        </div>
        <div class="form-group row">
            <label for="id_weight" class="col-sm-2 col-form-label">Comment</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="id_weight" name="comment" maxlength="50"
                       value="{{ rating.comment }}" required>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

templates/ratings.html
{% extends "base.html" %}

{% block title %}Ratings{% endblock %}

{% block content %}
    {% for dish in page_obj.object_list %}
        <div class="card shadow mb-4 ml-4 mr-4">
            <!-- Card Header - Accordion -->
            <a href="#collapseCardExample{{ dish.pk }}" class="d-block card-header py-3" data-toggle="collapse"
               role="button"
               aria-expanded="true" aria-controls="collapseCardExample">
                <h6 class="m-0 font-weight-bold text-primary">{{ dish.user.username }}</h6>
            </a>
            <!-- Card Content - Collapse -->
            <div class="collapse show" id="collapseCardExample{{ dish.pk }}">
                <div class="card-body">
                    {{ dish.score }}
                    <br/>
                    {{ dish.comment }}
                    <br/>
                    {{ dish.updated_at }}
                </div>
            </div>
        </div>
    {% endfor %}
    <div class="mb-4">
        <div class="pagination d-flex justify-content-center">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a class="btn btn-primary" href="?page=1">&laquo; first</a>
                <a class="btn btn-primary" href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                <button class="btn btn-secondary"
                        disabled>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</button>
            </span>

            {% if page_obj.has_next %}
                <a class="btn btn-primary" href="?page={{ page_obj.next_page_number }}">next</a>
                <a class="btn btn-primary" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
        </div>
    </div>
{% endblock %}