django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('foods.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foods/urls.py
from django.urls import path, include

from . import user_views, dish_views, menu_views

urlpatterns = [
    path('', dish_views.AllPublicDishView.as_view(), name='index'),
    path('accounts/', include([
        path('register/', user_views.RegisterView.as_view(), name='register'),
    ])),
    path('users/', include([
        path('profile/', user_views.UpdateProfileView.as_view(), name='account_profile'),
        path('dish/', include([
            path('', dish_views.UserAllDishView.as_view(), name='user_all_dishes'),
            path('add/', dish_views.CreateDishView.as_view(), name='user_add_dish'),
            path('<int:pk>/', include([
                path('', dish_views.UserDishView.as_view(), name='user_dish_detail'),
                path('update/', dish_views.UpdateDishView.as_view(), name='user_update_dish'),
                path('delete/', dish_views.DeleteDishView.as_view(), name='user_delete_dish')
            ]))
        ]))
    ])),
    path('admins/', include([
        # path('', admin_views.Index.as_view(), name='admin_index'),
        # path('user/', admin_views.UserManagement.as_view(), name='user_management'),
        path('profile/', user_views.AdminSearchProfile.as_view(), name='admin_search_profile'),
        path('dish/', include([
            path('', dish_views.AdminAllDishView.as_view(), name='admin_all_dishes'),
            path('add/', dish_views.CreateDishView.as_view(), name='admin_add_dish'),
            path('<int:pk>/', include([
                path('', dish_views.AdminDishView.as_view(), name='admin_dish_detail'),
                path('update/', dish_views.UpdateDishView.as_view(), name='admin_update_dish'),
                path('delete/', dish_views.DeleteDishView.as_view(), name='admin_delete_dish')
            ]))
        ])),
    ])),
    path('dish/', include([
        path('', dish_views.SearchDishView.as_view(), name='search_dish'),
        path('<int:pk>/', include([
            path('', dish_views.DishDetailView.as_view(), name='dish_detail'),
            path('rate/', dish_views.UserRatingView.as_view(), name='user_rating'),
            path('delete/', dish_views.SuperuserDeleteDishView.as_view(), name='self_delete_dish')
        ])),
    ])),
    path('profile/', include([
        path('', user_views.SearchProfile.as_view(), name='search_profile'),
        path('<int:pk>/', include([
            path('', user_views.ProfileView.as_view(), name='profile_detail'),
            path('activate/', user_views.UpdateActivationView.as_view(), name='update_activation')
        ])),
    ])),

    path('menu/', include([
        path('', menu_views.index.as_view(), name="menu_index"),
        path('create', menu_views.create.as_view(), name="menu_create"),
        path('create_query', menu_views.create_query.as_view(), name="menu_create_query"),
        path('update_query', menu_views.update_query.as_view(), name="menu_update_query"),
        path('clone_query', menu_views.clone_query.as_view(), name="menu_clone_query"),
        path('delete_query', menu_views.delete_query.as_view(), name="menu_delete_query"),
        path('history', menu_views.history.as_view(), name="menu_history"),
        path('detail/<int:menu_id>', menu_views.detail.as_view(), name="menu_detail"),
        path('update', menu_views.update.as_view(), name="menu_update"),
        path('delete', menu_views.delete.as_view(), name="menu_delete"),
        path('query_filter_dish', menu_views.query_filter_dish, name="menu_query_filter_dish")
    ]))
]

handler404 = 'foods.views.error_404'
handler500 = 'foods.views.error_500'

foods/models.py
from django.contrib.auth.models import User as BaseUser
from django.db import models

from foods.validators import dish_image_path


class User(models.Model):
    user = models.OneToOneField(BaseUser, on_delete=models.CASCADE)
    birthday = models.DateField()
    height = models.IntegerField()
    weight = models.IntegerField()
    gender = models.BooleanField()
    diet_factor = models.FloatField()

    def __str__(self):
        return self.user.username

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=models.Q(weight__gt=0),
                name='weight_gt_0'
            ),
            models.CheckConstraint(
                check=models.Q(height__gt=100),
                name='height_gt_100'
            ),
            models.CheckConstraint(
                check=models.Q(diet_factor__gt=0),
                name='diet_factor_gt_0'
            )
        ]


class Dish(models.Model):
    user = models.ForeignKey(BaseUser, on_delete=models.CASCADE)
    dish_name = models.CharField(max_length=50)
    description = models.CharField(max_length=500)
    calories = models.IntegerField()
    is_public = models.BooleanField()
    image = models.ImageField(
        upload_to=dish_image_path
    )
    ingredients = models.CharField(max_length=250)
    score = models.FloatField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.dish_name

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=models.Q(calories__gt=0),
                name='calories_gt_0'
            ),
            models.CheckConstraint(
                check=models.Q(score__gte=0),
                name='dish_score_gte_0'
            ),
            models.CheckConstraint(
                check=models.Q(score__lte=5),
                name='dish_score_lte_5'
            )
        ]
        ordering = ['-updated_at']


class Rating(models.Model):
    user = models.ForeignKey(BaseUser, on_delete=models.CASCADE)
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE)
    score = models.IntegerField()
    comment = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user.pk}-{self.dish.pk}'

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=models.Q(score__gt=0),
                name='rating_score_gt_0'
            ),
            models.CheckConstraint(
                check=models.Q(score__lte=5),
                name='rating_score_lte_5'
            ),
        ]
        unique_together = ('user', 'dish')
        ordering = ['-updated_at']


class Menu(models.Model):
    user = models.ForeignKey(BaseUser, on_delete=models.CASCADE)
    description = models.CharField(max_length=250)
    mealtime = models.DateTimeField()
    limit = models.IntegerField()
    dishes = models.ManyToManyField(Dish, null=True, through="Menu_Dish")

    # calories it not necessary but db keep it in local, i am not able to fix it
    calories = models.IntegerField(default=0)


class Menu_Dish(models.Model):
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE)
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE)
    count = models.IntegerField(default=1)

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=models.Q(count__gt=0),
                name="count_gt_0"
            )
        ]

foods/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm, CharField, EmailField, EmailInput

from .models import Dish, User, Rating


class BaseUserForm(UserCreationForm):
    email = EmailField(
        label='Email',
        widget=EmailInput(),
        max_length=50
    )
    first_name = CharField(
        label='First name',
        max_length=50
    )
    last_name = CharField(
        label='Last name',
        max_length=50
    )

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.email = self.cleaned_data.get('email')
        user.first_name = self.cleaned_data.get('first_name')
        user.last_name = self.cleaned_data.get('last_name')
        if commit:
            user.save()
        return user


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['birthday', 'height', 'weight', 'gender', 'diet_factor']


class DishForm(ModelForm):
    class Meta:
        model = Dish
        fields = ['dish_name', 'description', 'calories', 'is_public', 'ingredients', 'image']


class RatingForm(ModelForm):
    class Meta:
        model = Rating
        fields = ['score', 'comment']

foods/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render
from django.views.generic import View
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView


def index(request):
    context = {
        'app_name': 'Foods'
    }
    return render(request, 'index.html', context)


class LoginRequiredView(LoginRequiredMixin, View):
    login_url = '/accounts/login'


class SelfLoginView(UserPassesTestMixin, LoginRequiredView):
    def test_func(self):
        pass


class UserOnlyView(SelfLoginView):
    def test_func(self):
        return not self.request.user.is_staff


class AdminOnlyView(SelfLoginView):
    def test_func(self):
        return self.request.user.is_staff


class UserDetailView(DetailView, UserOnlyView):
    def test_func(self):
        return super().test_func() and (self.request.user.pk == self.get_object().user.pk)


class UserListView(ListView, UserOnlyView):
    def test_func(self):
        return super().test_func()


class UserCreateView(CreateView, UserOnlyView):
    def test_func(self):
        return super().test_func() and (self.request.user.pk == self.get_object().user.pk)


class UserUpdateView(UpdateView, UserOnlyView):
    def test_func(self):
        return super().test_func() and (self.request.user.pk == self.get_object().user.pk)


class UserDeleteView(DeleteView, UserOnlyView):
    def test_func(self):
        return super().test_func() and (self.request.user.pk == self.get_object().user.pk)


class AdminDetailView(DetailView, AdminOnlyView):
    def test_func(self):
        return super().test_func() and (self.request.user.pk == self.get_object().user.pk)


class AdminListView(ListView, AdminOnlyView):
    def test_func(self):
        return super().test_func()


class AdminCreateView(CreateView, AdminOnlyView):
    def test_func(self):
        return super().test_func() and (self.request.user.pk == self.get_object().user.pk)


class AdminUpdateView(UpdateView, AdminOnlyView):
    def test_func(self):
        return super().test_func() and (self.request.user.pk == self.get_object().user.pk)


class AdminDeleteView(DeleteView, AdminOnlyView):
    def test_func(self):
        return super().test_func() and (self.request.user.pk == self.get_object().user.pk)


class SelfCreateView(CreateView, SelfLoginView):
    def test_func(self):
        return self.request.user.pk == self.get_object().user.pk


class SelfUpdateView(UpdateView, SelfLoginView):
    def test_func(self):
        return self.request.user.pk == self.get_object().user.pk


class SelfDeleteView(DeleteView, SelfLoginView):
    def test_func(self):
        return self.request.user.pk == self.get_object().user.pk


class SuperuserDeleteView(DeleteView, SelfLoginView):
    def test_func(self):
        user = self.request.user
        return user.is_staff or (user.pk == self.get_object().user.pk)


def error_404(request, exception):
    return render(request, 'error.html')


def error_500(request):
    return render(request, 'error.html')

templates/foods/dish.html
{% extends "base.html" %}

{% block title %}Dish{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {% for field in form.visible_fields %}
            <div class="fieldWrapper">
                {{ field.dish_name }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

templates/foods/dish_add.html
{% extends "base.html" %}

{% block title %}Dish{% endblock %}

{% block content %}
    <div class="mt-5"><h2 class="text-center">Thêm món ăn</h2></div>
    {% if form %}
        {% for field in form %}
            {% if field.errors %}
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <div>{{field.label_tag}} {{ field.errors }}</div>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    <form class="m-5" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group row">
            <label for="id_dish_name" class="col-sm-2 col-form-label">Tên món ăn:</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="id_dish_name" name="dish_name" value="" required>
            </div>
        </div>
        <div class="form-group row">
            <label for="id_description" class="col-sm-2 col-form-label">Mô tả:</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="id_description" name="description"
                       value="" required>
            </div>
        </div>
        <div class="form-group row">
            <label for="id_calories" class="col-sm-2 col-form-label">Lượng calories (kcal):</label>
            <div class="col-sm-10">
                <input type="number" class="form-control" id="id_calories" name="calories" value="" required>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-2">Trạng thái:</div>
            <div class="col-sm-10">
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="id_is_public" name="is_public">
                    <label class="form-check-label" for="id_is_public">
                        Công khai
                    </label>
                </div>
            </div>
        </div>
        <div class="form-group row">
            <label for="id_ingredients" class="col-sm-2 col-form-label">Thành phần:</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="id_ingredients" name="ingredients"
                       value="" required>
            </div>
        </div>
        <div class="form-group row">
            <label for="id_image" class="col-sm-2 col-form-label">Ảnh minh hoạ:</label>
            <input type="file" class="form-control-file col-sm-10" id="id_image" name="image" required>
        </div>
        <div class="form-group row">
            <div class="col-sm-2"></div>
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Tạo món ăn</button>
            </div>
        </div>
    </form>
{% endblock %}

templates/foods/dish_confirm_delete.html
{% extends "base.html" %}

{% block title %}Dish{% endblock %}

{% block content %}
    <form class="m-5" method="post">
        {% csrf_token %}
        <p>Bạn có chắc muốn xóa "{{ object }}"?</p>
        <input type="submit" class="btn btn-primary" value="Xác nhận">
    </form>
{% endblock %}

templates/foods/dish_form.html
{% extends "base.html" %}

{% block title %}Dish{% endblock %}

{% block content %}
    <div class="mt-5"><h2 class="text-center">Chỉnh sửa món ăn</h2></div>
    {% if form %}
        {% for field in form %}
            {% if field.errors %}
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <div>{{field.label_tag}} {{ field.errors }}</div>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    <form class="m-5" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group row">
            <label for="id_dish_name" class="col-sm-2 col-form-label">Tên món ăn:</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="id_dish_name" name="dish_name"
                       value="{{ form.dish_name.value }}" required>
            </div>
        </div>
        <div class="form-group row">
            <label for="id_description" class="col-sm-2 col-form-label">Mô tả:</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="id_description" name="description"
                       value="{{ form.description.value }}" required>
            </div>
        </div>
        <div class="form-group row">
            <label for="id_calories" class="col-sm-2 col-form-label">Lượng calories (kcal):</label>
            <div class="col-sm-10">
                <input type="number" class="form-control" id="id_calories" name="calories"
                       value="{{ form.calories.value }}" required>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-2">Trạng thái:</div>
            <div class="col-sm-10">
                <div class="form-check">
                    {% if form.is_public.value %}
                        <input type="checkbox" class="form-check-input" id="id_is_public" name="is_public" checked>
                    {% else %}
                        <input type="checkbox" class="form-check-input" id="id_is_public" name="is_public">
                    {% endif %}
                    <label class="form-check-label" for="id_is_public">
                        Công khai
                    </label>
                </div>
            </div>
        </div>
        <div class="form-group row">
            <label for="id_ingredients" class="col-sm-2 col-form-label">Thành phần:</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="id_ingredients" name="ingredients"
                       value="{{ form.ingredients.value }}" required>
            </div>
        </div>
        <div class="form-group row">
            <label for="id_image" class="col-sm-2 col-form-label">Ảnh minh hoạ:</label>
            <input type="file" class="form-control-file col-sm-10" id="id_image" name="image" value="{{ form.image.value }}">
        </div>
        <div class="form-group row">
            <div class="col-sm-2"></div>
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Lưu thay đổi</button>
            </div>
        </div>
    </form>
{% endblock %}

templates/foods/menu.html
{% extends "base.html" %}

{% block title %}Menu{% endblock %}

{% block content %}

{% endblock %}

templates/foods/menus.html
{% extends "base.html" %}

{% block title %}Menus{% endblock %}

{% block content %}

{% endblock %}

templates/foods/user_form.html
{% extends "base.html" %}

{% block title %}Profile{% endblock %}

{% block content %}
    <form action="" method="post">
        {#        {% for field in form.visible_fields %}#}
        {#            <div class="fieldWrapper">#}
        {#                {{ field.errors }}#}
        {#                {{ field.label_tag }} {{ field }}#}
        {#            </div>#}
        {#        {% endfor %}#}
        {{ form }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}